sc_message:
    resource: "@SCMessageBundle/Resources/config/routing.yml"
    prefix:   /

sc_user:
    resource: "@SCUserBundle/Controller/"
    type:     annotation
    prefix:   /

sc_demo:
    resource: "@SCDemoBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
